---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-demo-master
  namespace: devops-mcm-demo
  labels:
    volume: jenkins-demo-master
    project: "devops-mcm-demo"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: NFS_SERVER_IP_ADDRESS
    path: /PATH/TO/NFS/VOLUME
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-demo-master-claim
  namespace: devops-mcm-demo
  labels:
    project: "devops-mcm-demo"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      volume: jenkins-demo-master
